# Generated by Django 5.1.6 on 2025-02-09 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('choices_level', models.CharField(choices=[('Essential', 'Essential'), ('Extra', 'Extra'), ('Deluxe', 'Deluxe')], max_length=70)),
                ('image', models.ImageField(upload_to='')),
                ('consoles', models.ManyToManyField(related_name='subscriptions', to='subscriptions.consoletype')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='subscriptions.subscriptionservice')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.FileField(upload_to='')),
                ('subscription_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='subscriptions.subscriptionservice')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('console_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='subscriptions.consoletype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subscription_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionperiod')),
                ('subscription_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='subscriptions.subscriptionservice')),
            ],
        ),
    ]
