# Generated by Django 4.2.19 on 2025-02-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionservice',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
